import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { BookData } from "@/types";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

async function Footer(){
  const response = await fetch(`${process.env.NEXT_PUBLIC_API_SERVER_URL}/book`,
    {cache: "force-cache"}
  );
  if(!response.ok){
    return <footer className="py-[100px] px-0 text-gray-400">
            제작 @JSE
          </footer>
  }
  const books: BookData[] = await response.json();
  const bookCount = books.length;

  return(
    <footer>
      <div>제작 @JSE</div>
      <div>{bookCount}개의 도서가 등록되어 있습니다.</div>
    </footer>
  )
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: ReactNode;
}>) {
  return (
    <html lang="en" className="m-0 p-0 bg-[rgba(250,_250,_250)]">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-0 p-0 bg-[rgba(250,_250,_250)]`}
      >
        <div className="max-w-[600px] min-h-screen mx-auto my-0 bg-white py-0 px-[15px] shadow-[0px_7px_29px_0px_rgba(100,_100,_111,_0.2)]">
          <header className="h-[60px] font-bold text-[18px] leading-[60px]">
            <Link href={'/'} className="text-black no-underline cursor-pointer">📚 ONEBITE BOOKS</Link>
          </header>
          <main className="pt-[10px]">
            {children}
          </main>
          <Footer />
        </div>
        {modal}
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
